import type { TrickCategory } from "@video-labeler/shared";

export const TRICK_NAMES: Record<TrickCategory, string[]> = {
  flip_trick: [
    "kickflip",
    "heelflip",
    "hardflip",
    "varial_kickflip",
    "varial_heelflip",
    "tre_flip",
    "laser_flip",
    "inward_heelflip",
    "double_kickflip",
    "double_heelflip",
  ],
  grind: [
    "50-50",
    "5-0",
    "nosegrind",
    "crooked_grind",
    "smith_grind",
    "feeble_grind",
    "overcrook",
    "salad_grind",
    "suski_grind",
    "willy_grind",
  ],
  slide: [
    "boardslide",
    "lipslide",
    "noseslide",
    "tailslide",
    "bluntslide",
    "nosebluntslide",
    "darkslide",
  ],
  manual: ["manual", "nose_manual"],
  air: [
    "ollie",
    "nollie",
    "fs_shove-it",
    "bs_shove-it",
    "no_comply_bs_shove-it",
    "no_comply_fs_shove-it",
    "fs_pop_shove-it",
    "bs_pop_shove-it",
    "fs_360_shove-it",
    "bs_360_shove-it",
  ],
  grab: [
    "melon",
    "indy",
    "stalefish",
    "nosegrab",
    "tailgrab",
    "benihana",
    "madonna",
    "method",
    "mute",
  ],
  transition: [
    "rock_to_fakie",
    "axle_stall",
    "blunt_to_fakie",
    "disaster",
    "feeble_stall",
    "smith_stall",
    "drop_in",
  ],
  combo: [],
  unknown: ["unknown"],
};

export const STANCE_PREFIXES = ["", "nollie_", "switch_", "fakie_"] as const;
export const DIRECTION_PREFIXES = ["", "bs_", "fs_"] as const;
